### ISSUE TITLE
Please Add Support for Blur Effect in Panels

### ISSUE THREAD

**Issue by SleepInfinity** [Dinno-DEV/zen-cleaned-url-bar#12]
Hello,

Just like the URL bar, I would like to make all the panels transparent and blurred (including the three-dots panel, extensions panel, downloads panel, right-click context menu, etc.).

I tried achieving this by modifying the CSS code, but no matter how hard I tried, I couldn't get the blur effect to work using `backdrop-filter`. I was only able to achieve transparency using the following code:

```css
:root {
  --arrowpanel-background: color-mix(in hsl, var(--mod-cleanedurlbar-customcolor), transparent var(--mod-cleanedurlbar-customtransparency)) !important;
}
```

If you can help me achieve this, I would really appreciate it.

Thank you!
